---
title: Scott's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  dogs:
    title: dogs
    output: true
  octopi:
    title: octopi
    output: true
  people:
    title: people
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
email: sanesham@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
permalink: pretty
baseurl: 
url: http://scottnesham.com
twitter_username: sevenfoxes
github_username: sevenfoxes
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- Gulpfile.js
- src
- yarn.lock
- package.json
- ".vscode"
