// flow-typed signature: cf36b7d305d35f7585b9989ded56a68a
// flow-typed version: <<STUB>>/connect-modrewrite_v^0.10.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-modrewrite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-modrewrite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-modrewrite/Gruntfile' {
  declare module.exports: any;
}

declare module 'connect-modrewrite/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-modrewrite/Gruntfile.js' {
  declare module.exports: $Exports<'connect-modrewrite/Gruntfile'>;
}
declare module 'connect-modrewrite/index' {
  declare module.exports: $Exports<'connect-modrewrite'>;
}
declare module 'connect-modrewrite/index.js' {
  declare module.exports: $Exports<'connect-modrewrite'>;
}
declare module 'connect-modrewrite/test/test.js' {
  declare module.exports: $Exports<'connect-modrewrite/test/test'>;
}
