// flow-typed signature: 1b4851f1b89bda82c8eafa478a20aac0
// flow-typed version: <<STUB>>/gulp-ejs_v^3.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-ejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-ejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-ejs/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-ejs/index' {
  declare module.exports: $Exports<'gulp-ejs'>;
}
declare module 'gulp-ejs/index.js' {
  declare module.exports: $Exports<'gulp-ejs'>;
}
declare module 'gulp-ejs/test/main.js' {
  declare module.exports: $Exports<'gulp-ejs/test/main'>;
}
