// flow-typed signature: 73fee0515b1fe854ec3ca266a694ac03
// flow-typed version: <<STUB>>/gulp-concat-css_v^2.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-concat-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-concat-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-concat-css/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-concat-css/index' {
  declare module.exports: $Exports<'gulp-concat-css'>;
}
declare module 'gulp-concat-css/index.js' {
  declare module.exports: $Exports<'gulp-concat-css'>;
}
declare module 'gulp-concat-css/test/test.js' {
  declare module.exports: $Exports<'gulp-concat-css/test/test'>;
}
