// flow-typed signature: 43ec2b743ec7b3bc77e8b645dd2445d9
// flow-typed version: <<STUB>>/postcss-namespace_v^1.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-namespace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-namespace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-namespace/build/index' {
  declare module.exports: any;
}

declare module 'postcss-namespace/examples/postcss' {
  declare module.exports: any;
}

declare module 'postcss-namespace/gulpfile.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-namespace/build/index.js' {
  declare module.exports: $Exports<'postcss-namespace/build/index'>;
}
declare module 'postcss-namespace/examples/postcss.js' {
  declare module.exports: $Exports<'postcss-namespace/examples/postcss'>;
}
declare module 'postcss-namespace/gulpfile.babel.js' {
  declare module.exports: $Exports<'postcss-namespace/gulpfile.babel'>;
}
declare module 'postcss-namespace/index' {
  declare module.exports: $Exports<'postcss-namespace'>;
}
declare module 'postcss-namespace/index.js' {
  declare module.exports: $Exports<'postcss-namespace'>;
}
