// flow-typed signature: 544420d861a5b6adf03383cd9d7e6f5e
// flow-typed version: <<STUB>>/redux-easy-actions_v^0.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-easy-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-easy-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-easy-actions/lib/core' {
  declare module.exports: any;
}

declare module 'redux-easy-actions/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-easy-actions/lib/core.js' {
  declare module.exports: $Exports<'redux-easy-actions/lib/core'>;
}
declare module 'redux-easy-actions/test/test.js' {
  declare module.exports: $Exports<'redux-easy-actions/test/test'>;
}
